app:
  desc: Gin框架学习实践
  version: v1.0.0
  addr: 0.0.0.0:8088
  env: prod
log:
  path: logs # 日志文件目录
  filePrefix: fasystem # 日志文件前缀
  fileFormat: 2006-01-02 # 日志文件名格式
  level: info # 最低记录级别
  outFormat: json # json/console
  lumberJack: # 日志文件切割和压缩
    maxSize: 1 # 单文件最大容量(单位MB)
    maxBackups: 3 # 保留旧文件的最大数量
    maxAge: 30 # 旧文件最多保存几天
    compress: false #是否压缩/归档旧文件
mysql:
  enable: true
  host: 172.20.0.1
  port: 3306
  user: root
  password: 8f818a3a11f6073c
  database: fund_analye_system
  charset: utf8mb4 # 要支持完整的UTF-8编码,需设置成: utf8mb4
  parseTime: true # 解析time.Time类型
  timeZone: Local # 时区,若设置 Asia/Shanghai,需写成: Asia%2fShanghai
  defaultStringSize: 255 # string 类型字段的默认长度
  disableDatetimePrecision: true # 禁用 datetime 精度，MySQL 5.6 之前的数据库不支持
  skipInitializeWithVersion: false # 根据当前 MySQL 版本自动配置
  autoMigrate: false # 开启时，每次服务启动都会根据实体创建/更新表结构
  slowSql: 50ms # 慢sql时间。单位毫秒
  logLevel: info # error、info、warn
  ignoreRecordNotFoundError: true # 是否忽略ErrRecordNotFound(未查到记录错误)
  gorm: # gorm配置项disableForeignKeyConstraintWhenMigrating
    skipDefaultTx: false # 是否跳过默认事务
    tablePrefix: "fas_" #表前缀
    singularTable: true # 是否使用单数表名(默认复数)，启用后，User结构体表将是user
    coverLogger: true # 是否覆盖默认logger
    prepareStmt: false # 执行任何SQL时都会创建一个prepared statement并将其缓存，以提高后续的效率
    disableForeignKeyConstraintWhenMigrating: true #在AutoMigrate 或 CreateTable 时，GORM 会自动创建外键约束，若要禁用该特性，可将其设置为 true
jwt:
  secret: liuqh.icu # jwt生成密钥
  issuer: 猿码记 # 签发人
  expire: 3h # 有效时间，值如: 30s|10min|1h
redis:
  enable: false
  addr: 172.20.0.1:6379
  password: # 密码(可为空)
  defaultDB: 0 # 默认DB
  dialTimeout: 5s #redis连接超时时间.默认5s
elastic:
  # 是否开启
  enable: false
  # 服务地址，多个地址用逗号隔开
  url: http://127.0.0.1:9200
  # 是否转换请求地址，默认为true,当等于true时 请求http://ip:port/_nodes/http，将其返回的url作为请求路径
  sniff: false
  # 心跳检测间隔
  healthCheckInterval: 5s
  # 日志前缀
  logPre: ES-
cron:
  # 是否开启
  enable: true