version: '3'
services:
  app:
    build:
      context: .
      args:
        - APP_ENV=${APP_ENV}
    command: sh -c "./app -c ./config.yaml"
    extra_hosts:
      - "dockerhost:${DOCKER_HOST_IP}"
    ports:
      - "${APP_PORT}:8088"