version: '3'
networks:
  backend:
    driver: ${NETWORKS_DRIVER}
services:
  app:
    build:
      context: .
      args:
        - APP_ENV=${APP_ENV}
    command: sh -c "./app -c ./config.yaml"
    ports:
      - "${APP_PORT}:8088"