version: '3'
networks:
  go_env:
    external: true
services:
  app:
    build:
      context: .
      args:
        - APP_ENV=${APP_ENV}
    command: sh -c "./app -c ./config.yaml"
    volumes:
      - ${PROJECT_PATH}/config-${APP_ENV}.yaml:/www/config.yaml
      - ${LOG_PATH}/logs:/www/logs
    ports:
      - "${APP_PORT}:8088"